In [1]:
#pip install numpy

In [2]:
import numpy as np

In [ ]:
help(np)

Here we shows all Numpy functions and methods that are available in the current environment. We can see that there are 1,000+ functions and methods available in the current environment.

In [ ]:
dir(np)

In [15]:
arr = np.array([1,2,3,4,5])

In [16]:
print(arr)

[1 2 3 4 5]


#numpy.sort() function

In [17]:
a = [1,2,8,9,6,1,3,6]
np.sort(a, kind='quicksort')

array([1, 1, 2, 3, 6, 6, 8, 9])

In [18]:
a = [1,2,8,9,6,1,3,6]
np.sort(a, kind='mergesort')

array([1, 1, 2, 3, 6, 6, 8, 9])

In [19]:
a = [1,2,8,9,6,1,3,6]
np.sort(a, kind='heapsort')

array([1, 1, 2, 3, 6, 6, 8, 9])

In [20]:
a = [1,2,8,9,6,1,3,6]
np.sort(a, kind='stable')

array([1, 1, 2, 3, 6, 6, 8, 9])

In [ ]:
a = [1,2,8,9,6,1,3,6]
np.sort(a, kind='')

Sort in Ascending Order

In [27]:
a = np.array([1,2,1,3])

In [30]:
a.sort(axis= -1, kind=None, order=None)

In [31]:
print(a)

[1 1 2 3]


Sort in Descending Order

In [32]:
a = np.array([1,2,1,3])
a[::-1].sort()
print(a)

[3 2 1 1]


Sort 2D Array

In [33]:
a = np.array([[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]])
np.sort(a, axis= 1, kind=None, order=None)

array([[10, 11, 13, 22],
       [ 7, 14, 20, 23],
       [11, 17, 31, 33]])

Sort 3D Array

In [35]:
a = np.array([[[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]], [[12, 11, 13, 23], [23, 7, 12, 14], [31, 34, 33, 17]], [[10, 6, 13, 22], [34, 7, 20, 14], [31, 34, 33, 7]]])

In [36]:
np.sort(a, axis= 2, kind=None, order=None)

array([[[10, 11, 13, 22],
        [ 7, 14, 20, 23],
        [11, 17, 31, 33]],

       [[11, 12, 13, 23],
        [ 7, 12, 14, 23],
        [17, 31, 33, 34]],

       [[ 6, 10, 13, 22],
        [ 7, 14, 20, 34],
        [ 7, 31, 33, 34]]])

np.where() with 3D array using NumPy

In [44]:
a = np.arange(1,11)

In [45]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
np.where(a < 5, a, 10*a)

array([  1,   2,   3,   4,  50,  60,  70,  80,  90, 100])

In [47]:
np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

In [48]:
x, y = np.ogrid[:3, :4]

In [49]:
np.where(x < y, x, 10 + y)

array([[10,  0,  0,  0],
       [10, 11,  1,  1],
       [10, 11, 12,  2]])

In [50]:
a = np.array([[0, 1, 2],[0, 2, 4],[0, 3, 6]])

In [51]:
np.where(a < 4, a, -1)  # -1 is broadcast

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])